package com.photoncam.film

import androidx.compose.ui.graphics.Color
import com.photoncam.R

object FilmCatalog {

    val all: List<FilmStock> = listOf(

        // ── Kodak ─────────────────────────────────────────────────────────────

        FilmStock(
            id = "kodak_kodachrome_25",
            brand = FilmBrand.KODAK,
            name = "Kodachrome 25",
            iso = 25,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.hald_kodak_kodachrome25,
            lutType = LutType.PNG,
            grainAmount = 0.01f,
            grainSize = 0.5f,
            lightLeakProbability = 0.03f,
            colorTempShift = +100,
            highlightRolloff = 0.30f,
            saturation = 1.35f,
            contrast = 1.30f,
            shadowLift = 0f,
            accentColor = Color(0xFFCC3322),
            description = "The immortal slide film. Saturated reds that never fade.",
        ),

        FilmStock(
            id = "cinestill_50d",
            brand = FilmBrand.CINESTILL,
            name = "50D",
            iso = 50,
            category = FilmCategory.COLOR,
            lutResId = null,
            grainAmount = 0.03f,
            grainSize = 0.6f,
            lightLeakProbability = 0.08f,
            colorTempShift = +30,
            highlightRolloff = 0.38f,
            saturation = 1.18f,
            contrast = 1.22f,
            shadowLift = 2f,
            accentColor = Color(0xFFEE5566),
            description = "Cinema precision in daylight. Ultra-fine, vivid.",
        ),

        FilmStock(
            id = "fuji_velvia_50",
            brand = FilmBrand.FUJI,
            name = "Velvia 50",
            iso = 50,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_fuji_velvia50,
            grainAmount = 0.02f,
            grainSize = 0.6f,
            lightLeakProbability = 0.03f,
            colorTempShift = -100,
            highlightRolloff = 0.26f,
            saturation = 1.75f,
            contrast = 1.32f,
            shadowLift = 0f,
            accentColor = Color(0xFF2D7D46),
            description = "Punchy greens, electric reds. Landscape obsession.",
        ),

        FilmStock(
            id = "ilford_panf_50",
            brand = FilmBrand.ILFORD,
            name = "Pan F Plus 50",
            iso = 50,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_panf50,
            lutType = LutType.PNG,
            grainAmount = 0.02f,
            grainSize = 0.5f,
            lightLeakProbability = 0.03f,
            colorTempShift = 0,
            highlightRolloff = 0.35f,
            saturation = 0f,
            contrast = 0.88f,
            shadowLift = 12f,
            accentColor = Color(0xFFE0E0E0),
            description = "Near grain-free. Maximum tonal range for slow light.",
        ),

        FilmStock(
            id = "kodak_kodachrome_64",
            brand = FilmBrand.KODAK,
            name = "Kodachrome 64",
            iso = 64,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.hald_kodak_kodachrome64,
            lutType = LutType.PNG,
            grainAmount = 0.02f,
            grainSize = 0.6f,
            lightLeakProbability = 0.04f,
            colorTempShift = +80,
            highlightRolloff = 0.30f,
            saturation = 1.30f,
            contrast = 1.26f,
            shadowLift = 0f,
            accentColor = Color(0xFFBB3322),
            description = "The working photographer's Kodachrome. Rich, precise.",
        ),

        FilmStock(
            id = "polaroid_669",
            brand = FilmBrand.POLAROID,
            name = "669",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.hald_polaroid_669,
            lutType = LutType.PNG,
            grainAmount = 0.22f,
            grainSize = 2.0f,
            lightLeakProbability = 0.30f,
            colorTempShift = +400,
            highlightRolloff = 0.55f,
            saturation = 0.75f,
            contrast = 0.82f,
            shadowLift = 20f,
            accentColor = Color(0xFFCC8844),
            description = "Classic pack film. Warm brown, soft edges, instant magic.",
        ),

        FilmStock(
            id = "rollei_retro_80s",
            brand = FilmBrand.ROLLEI,
            name = "Retro 80S",
            iso = 80,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_rollei_retro80s,
            lutType = LutType.PNG,
            grainAmount = 0.10f,
            grainSize = 1.1f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.44f,
            saturation = 0f,
            contrast = 0.95f,
            shadowLift = 12f,
            accentColor = Color(0xFFBBAA88),
            description = "80s archive aesthetics. Warm B&W, soft tonality.",
        ),

        FilmStock(
            id = "agfa_apx_100",
            brand = FilmBrand.AGFA,
            name = "APX 100",
            iso = 100,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_agfa_apx100,
            lutType = LutType.PNG,
            grainAmount = 0.05f,
            grainSize = 0.7f,
            lightLeakProbability = 0.03f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0f,
            contrast = 1.02f,
            shadowLift = 7f,
            accentColor = Color(0xFFCCCCCC),
            description = "European B&W precision. Clean, neutral, accurate.",
        ),

        FilmStock(
            id = "agfa_precisa_100",
            brand = FilmBrand.AGFA,
            name = "Precisa CT 100",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.hald_agfa_precisa100,
            lutType = LutType.PNG,
            grainAmount = 0.04f,
            grainSize = 0.7f,
            lightLeakProbability = 0.05f,
            colorTempShift = -100,
            highlightRolloff = 0.28f,
            saturation = 1.40f,
            contrast = 1.35f,
            shadowLift = 0f,
            accentColor = Color(0xFF40BBAA),
            description = "Cross-process teal & orange. Slide film gone wild.",
        ),

        FilmStock(
            id = "agfa_ultra_color_100",
            brand = FilmBrand.AGFA,
            name = "Ultra Color 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_agfa_ultra_color100,
            lutType = LutType.PNG,
            grainAmount = 0.04f,
            grainSize = 0.7f,
            lightLeakProbability = 0.05f,
            colorTempShift = +80,
            highlightRolloff = 0.36f,
            saturation = 1.50f,
            contrast = 1.18f,
            shadowLift = 0f,
            accentColor = Color(0xFF40CC80),
            description = "Ultra-vivid European color. Bold, saturated, punchy.",
        ),

        FilmStock(
            id = "fuji_acros_100",
            brand = FilmBrand.FUJI,
            name = "Acros 100",
            iso = 100,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_fuji_acros100,
            lutType = LutType.PNG,
            grainAmount = 0.03f,
            grainSize = 0.6f,
            lightLeakProbability = 0.03f,
            colorTempShift = 0,
            highlightRolloff = 0.45f,
            saturation = 0f,
            contrast = 1.04f,
            shadowLift = 6f,
            accentColor = Color(0xFFCCCCCC),
            description = "The finest grain in B&W. Shadow gradation perfection.",
        ),

        FilmStock(
            id = "fuji_provia_100f",
            brand = FilmBrand.FUJI,
            name = "Provia 100F",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_fuji_provia100f,
            grainAmount = 0.04f,
            grainSize = 0.7f,
            lightLeakProbability = 0.04f,
            colorTempShift = -30,
            highlightRolloff = 0.32f,
            saturation = 1.15f,
            contrast = 1.22f,
            shadowLift = 0f,
            accentColor = Color(0xFF5BA4CF),
            description = "Neutral, accurate slide film. Faithful reproduction.",
        ),

        FilmStock(
            id = "fuji_superia_100",
            brand = FilmBrand.FUJI,
            name = "Superia 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_superia100,
            lutType = LutType.PNG,
            grainAmount = 0.05f,
            grainSize = 0.8f,
            lightLeakProbability = 0.05f,
            colorTempShift = -80,
            highlightRolloff = 0.38f,
            saturation = 1.05f,
            contrast = 1.10f,
            shadowLift = 3f,
            accentColor = Color(0xFF55AADD),
            description = "Clean, cool everyday color. Fine grain consumer.",
        ),

        FilmStock(
            id = "ilford_delta_100",
            brand = FilmBrand.ILFORD,
            name = "Delta 100",
            iso = 100,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_delta100,
            lutType = LutType.PNG,
            grainAmount = 0.04f,
            grainSize = 0.65f,
            lightLeakProbability = 0.03f,
            colorTempShift = 0,
            highlightRolloff = 0.38f,
            saturation = 0f,
            contrast = 0.96f,
            shadowLift = 8f,
            accentColor = Color(0xFFD5D5D5),
            description = "Delta perfection at 100. Silky grain, wide latitude.",
        ),

        FilmStock(
            id = "kodak_ektachrome_100vs",
            brand = FilmBrand.KODAK,
            name = "Ektachrome 100 VS",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.hald_kodak_ektachrome100vs,
            lutType = LutType.PNG,
            grainAmount = 0.04f,
            grainSize = 0.7f,
            lightLeakProbability = 0.04f,
            colorTempShift = -60,
            highlightRolloff = 0.28f,
            saturation = 1.45f,
            contrast = 1.35f,
            shadowLift = 0f,
            accentColor = Color(0xFF3366CC),
            description = "Vivid Saturation slide. Maximum color punch.",
        ),

        FilmStock(
            id = "kodak_ektachrome_e100",
            brand = FilmBrand.KODAK,
            name = "Ektachrome E100",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.hald_kodak_ektachrome_e100,
            lutType = LutType.PNG,
            grainAmount = 0.04f,
            grainSize = 0.7f,
            lightLeakProbability = 0.04f,
            colorTempShift = -80,
            highlightRolloff = 0.32f,
            saturation = 1.22f,
            contrast = 1.28f,
            shadowLift = 0f,
            accentColor = Color(0xFF5599DD),
            description = "Cool slide precision. Blues that cut like glass.",
        ),

        FilmStock(
            id = "kodak_ektar_100",
            brand = FilmBrand.KODAK,
            name = "Ektar 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_ektar100,
            lutType = LutType.PNG,
            grainAmount = 0.03f,
            grainSize = 0.7f,
            lightLeakProbability = 0.04f,
            colorTempShift = +60,
            highlightRolloff = 0.42f,
            saturation = 1.60f,
            contrast = 1.20f,
            shadowLift = 0f,
            accentColor = Color(0xFFE8A52A),
            description = "Ultra-fine grain, hyper-saturated landscapes.",
        ),

        FilmStock(
            id = "kodak_elite100_xpro",
            brand = FilmBrand.KODAK,
            name = "Elite Chrome 100 XPro",
            iso = 100,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.hald_kodak_elite100_xpro,
            lutType = LutType.PNG,
            grainAmount = 0.06f,
            grainSize = 0.8f,
            lightLeakProbability = 0.15f,
            colorTempShift = +200,
            highlightRolloff = 0.28f,
            saturation = 1.45f,
            contrast = 1.38f,
            shadowLift = 0f,
            accentColor = Color(0xFFCC6633),
            description = "Slide film processed wrong. Teal, orange, electric.",
        ),

        FilmStock(
            id = "kodak_tmax_100",
            brand = FilmBrand.KODAK,
            name = "T-MAX 100",
            iso = 100,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_kodak_tmax100,
            lutType = LutType.PNG,
            grainAmount = 0.04f,
            grainSize = 0.6f,
            lightLeakProbability = 0.03f,
            colorTempShift = 0,
            highlightRolloff = 0.38f,
            saturation = 0f,
            contrast = 1.08f,
            shadowLift = 5f,
            accentColor = Color(0xFFD8D8D8),
            description = "Clinical sharpness, near-invisible grain.",
        ),

        FilmStock(
            id = "polaroid_690",
            brand = FilmBrand.POLAROID,
            name = "690",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.hald_polaroid_690,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.8f,
            lightLeakProbability = 0.28f,
            colorTempShift = +300,
            highlightRolloff = 0.52f,
            saturation = 0.78f,
            contrast = 0.85f,
            shadowLift = 18f,
            accentColor = Color(0xFFDDAA77),
            description = "Last generation pack film. Warm, dreamy, classic.",
        ),

        FilmStock(
            id = "polaroid_px100uv_cold",
            brand = FilmBrand.POLAROID,
            name = "PX-100 UV+ Cold",
            iso = 100,
            category = FilmCategory.INSTANT,
            isBlackAndWhite = true,
            lutResId = R.raw.hald_polaroid_px100uv_cold,
            lutType = LutType.PNG,
            grainAmount = 0.22f,
            grainSize = 2.0f,
            lightLeakProbability = 0.28f,
            colorTempShift = -200,
            highlightRolloff = 0.50f,
            saturation = 0f,
            contrast = 0.88f,
            shadowLift = 22f,
            accentColor = Color(0xFF99AABB),
            description = "Cold B&W integral film. Icy shadows, ethereal tone.",
        ),

        FilmStock(
            id = "polaroid_timezero_expired",
            brand = FilmBrand.POLAROID,
            name = "Time Zero Expired",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.hald_polaroid_timezero_expired,
            lutType = LutType.PNG,
            grainAmount = 0.28f,
            grainSize = 2.5f,
            lightLeakProbability = 0.40f,
            colorTempShift = +300,
            highlightRolloff = 0.48f,
            saturation = 0.65f,
            contrast = 0.75f,
            shadowLift = 30f,
            accentColor = Color(0xFF9988AA),
            description = "Expired dreams. Unpredictable shifts, ghostly glow.",
        ),

        FilmStock(
            id = "rollei_ortho_25",
            brand = FilmBrand.ROLLEI,
            name = "Ortho 25",
            iso = 25,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_rollei_ortho25,
            lutType = LutType.PNG,
            grainAmount = 0.02f,
            grainSize = 0.5f,
            lightLeakProbability = 0.03f,
            colorTempShift = 0,
            highlightRolloff = 0.35f,
            saturation = 0f,
            contrast = 1.10f,
            shadowLift = 5f,
            accentColor = Color(0xFF8899BB),
            description = "Orthochromatic sensitivity. Blue sky burns, skin glows.",
        ),

        FilmStock(
            id = "rollei_retro_100",
            brand = FilmBrand.ROLLEI,
            name = "Retro 100 Tonal",
            iso = 100,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_rollei_retro100,
            lutType = LutType.PNG,
            grainAmount = 0.06f,
            grainSize = 0.8f,
            lightLeakProbability = 0.04f,
            colorTempShift = 0,
            highlightRolloff = 0.42f,
            saturation = 0f,
            contrast = 0.98f,
            shadowLift = 8f,
            accentColor = Color(0xFFBBBBBB),
            description = "Retro tonal gradation. Smooth B&W for any subject.",
        ),

        FilmStock(
            id = "ilford_fp4",
            brand = FilmBrand.ILFORD,
            name = "FP4 Plus",
            iso = 125,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_fp4plus,
            lutType = LutType.PNG,
            grainAmount = 0.05f,
            grainSize = 0.8f,
            lightLeakProbability = 0.04f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0f,
            contrast = 0.92f,
            shadowLift = 10f,
            accentColor = Color(0xFFD0D0D0),
            description = "Fine grain, wide latitude. The studio workhorse.",
        ),

        FilmStock(
            id = "fuji_160c",
            brand = FilmBrand.FUJI,
            name = "160C",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_160c,
            lutType = LutType.PNG,
            grainAmount = 0.06f,
            grainSize = 0.8f,
            lightLeakProbability = 0.04f,
            colorTempShift = -60,
            highlightRolloff = 0.65f,
            saturation = 0.85f,
            contrast = 0.82f,
            shadowLift = 20f,
            accentColor = Color(0xFF88B8D8),
            description = "Studio softness. Pastel, cool, perfect skin.",
        ),

        FilmStock(
            id = "kodak_portra_160",
            brand = FilmBrand.KODAK,
            name = "Portra 160",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_portra160,
            lutType = LutType.PNG,
            grainAmount = 0.07f,
            grainSize = 0.9f,
            lightLeakProbability = 0.06f,
            colorTempShift = +180,
            highlightRolloff = 0.68f,
            saturation = 0.82f,
            contrast = 0.80f,
            shadowLift = 22f,
            accentColor = Color(0xFFE8C070),
            description = "Portrait softness, half the grain of 400.",
        ),

        FilmStock(
            id = "polaroid_672",
            brand = FilmBrand.POLAROID,
            name = "672",
            iso = 160,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.hald_polaroid_672,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.8f,
            lightLeakProbability = 0.25f,
            colorTempShift = +250,
            highlightRolloff = 0.56f,
            saturation = 0.80f,
            contrast = 0.87f,
            shadowLift = 16f,
            accentColor = Color(0xFFCC9966),
            description = "Pro pack film, warm and rich. Reliable instant magic.",
        ),

        FilmStock(
            id = "polaroid_px680",
            brand = FilmBrand.POLAROID,
            name = "PX-680",
            iso = 160,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.hald_polaroid_px680,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.9f,
            lightLeakProbability = 0.25f,
            colorTempShift = +50,
            highlightRolloff = 0.60f,
            saturation = 0.80f,
            contrast = 0.88f,
            shadowLift = 25f,
            accentColor = Color(0xFFAA99BB),
            description = "600 film reborn. Dreamy fade, unexpected colour shifts.",
        ),

        FilmStock(
            id = "polaroid_px70",
            brand = FilmBrand.POLAROID,
            name = "PX-70",
            iso = 160,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.hald_polaroid_px70,
            lutType = LutType.PNG,
            grainAmount = 0.22f,
            grainSize = 2.0f,
            lightLeakProbability = 0.25f,
            colorTempShift = +200,
            highlightRolloff = 0.58f,
            saturation = 0.72f,
            contrast = 0.85f,
            shadowLift = 22f,
            accentColor = Color(0xFFDDAA66),
            description = "SX-70 at its warmest. Vintage instant nostalgia.",
        ),

        FilmStock(
            id = "agfa_vista_200",
            brand = FilmBrand.AGFA,
            name = "Vista 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_agfa_vista200,
            lutType = LutType.PNG,
            grainAmount = 0.10f,
            grainSize = 1.1f,
            lightLeakProbability = 0.10f,
            colorTempShift = +200,
            highlightRolloff = 0.48f,
            saturation = 1.18f,
            contrast = 0.98f,
            shadowLift = 8f,
            accentColor = Color(0xFF50B090),
            description = "Warm, vivid, affordable. European 90s color.",
        ),

        FilmStock(
            id = "fuji_superia_200",
            brand = FilmBrand.FUJI,
            name = "Superia 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_superia200,
            lutType = LutType.PNG,
            grainAmount = 0.07f,
            grainSize = 0.9f,
            lightLeakProbability = 0.07f,
            colorTempShift = -60,
            highlightRolloff = 0.44f,
            saturation = 1.06f,
            contrast = 1.08f,
            shadowLift = 4f,
            accentColor = Color(0xFF5AAEDC),
            description = "Cool, clean 200-speed everyday film. Reliable and versatile.",
        ),

        FilmStock(
            id = "fuji_superia_200_xpro",
            brand = FilmBrand.FUJI,
            name = "Superia 200 XPro",
            iso = 200,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.hald_fuji_superia200_xpro,
            lutType = LutType.PNG,
            grainAmount = 0.12f,
            grainSize = 1.3f,
            lightLeakProbability = 0.20f,
            colorTempShift = +100,
            highlightRolloff = 0.28f,
            saturation = 1.40f,
            contrast = 1.32f,
            shadowLift = 0f,
            accentColor = Color(0xFF44BBAA),
            description = "C-41 run wrong. Teal, yellow, unpredictable.",
        ),

        FilmStock(
            id = "kodak_colorplus_200",
            brand = FilmBrand.KODAK,
            name = "ColorPlus 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = null,
            grainAmount = 0.09f,
            grainSize = 1.1f,
            lightLeakProbability = 0.10f,
            colorTempShift = +250,
            highlightRolloff = 0.55f,
            saturation = 1.02f,
            contrast = 0.88f,
            shadowLift = 14f,
            accentColor = Color(0xFFE8B84B),
            description = "Affordable warmth. The corner-store roll.",
        ),

        FilmStock(
            id = "kodak_elite_color200",
            brand = FilmBrand.KODAK,
            name = "Elite Color 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_elite_color200,
            lutType = LutType.PNG,
            grainAmount = 0.08f,
            grainSize = 0.9f,
            lightLeakProbability = 0.08f,
            colorTempShift = +120,
            highlightRolloff = 0.46f,
            saturation = 1.20f,
            contrast = 1.05f,
            shadowLift = 6f,
            accentColor = Color(0xFFE89040),
            description = "Consumer slide quality at print film price.",
        ),

        FilmStock(
            id = "kodak_gold_200",
            brand = FilmBrand.KODAK,
            name = "Gold 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_kodak_gold200,
            grainAmount = 0.08f,
            grainSize = 1.0f,
            lightLeakProbability = 0.10f,
            colorTempShift = +350,
            highlightRolloff = 0.52f,
            saturation = 1.12f,
            contrast = 0.90f,
            shadowLift = 12f,
            accentColor = Color(0xFFFFD700),
            description = "Sunny, golden-hour warmth. The family holiday roll.",
        ),

        FilmStock(
            id = "kodak_kodachrome_200",
            brand = FilmBrand.KODAK,
            name = "Kodachrome 200",
            iso = 200,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.hald_kodak_kodachrome200,
            lutType = LutType.PNG,
            grainAmount = 0.07f,
            grainSize = 1.0f,
            lightLeakProbability = 0.05f,
            colorTempShift = +100,
            highlightRolloff = 0.32f,
            saturation = 1.25f,
            contrast = 1.22f,
            shadowLift = 0f,
            accentColor = Color(0xFFCC5533),
            description = "Kodachrome at speed. Vivid colour, iconic contrast.",
        ),

        FilmStock(
            id = "lomo_xpro",
            brand = FilmBrand.LOMOGRAPHY,
            name = "Cross Process",
            iso = 200,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.lut_lomo_xpro,
            grainAmount = 0.14f,
            grainSize = 1.5f,
            lightLeakProbability = 0.28f,
            colorTempShift = +250,
            highlightRolloff = 0.30f,
            saturation = 1.55f,
            contrast = 1.42f,
            shadowLift = 0f,
            accentColor = Color(0xFFFF6B35),
            description = "C-41 soup in E-6 chemistry. Unpredictable art.",
        ),

        FilmStock(
            id = "lomo_redscale_xr",
            brand = FilmBrand.LOMOGRAPHY,
            name = "Redscale XR",
            iso = 200,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.hald_lomo_redscale,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.8f,
            lightLeakProbability = 0.30f,
            colorTempShift = +800,
            highlightRolloff = 0.28f,
            saturation = 1.35f,
            contrast = 1.20f,
            shadowLift = 0f,
            accentColor = Color(0xFFDD4400),
            description = "Exposed through the base. All red, no rules.",
        ),

        FilmStock(
            id = "lomo_xpro_slide_200",
            brand = FilmBrand.LOMOGRAPHY,
            name = "X-Pro Slide 200",
            iso = 200,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.hald_lomo_xpro_slide,
            lutType = LutType.PNG,
            grainAmount = 0.16f,
            grainSize = 1.5f,
            lightLeakProbability = 0.25f,
            colorTempShift = +150,
            highlightRolloff = 0.26f,
            saturation = 1.50f,
            contrast = 1.38f,
            shadowLift = 0f,
            accentColor = Color(0xFF44CCAA),
            description = "Slide film cross-processed. Electric cyan and yellow.",
        ),

        FilmStock(
            id = "ilford_sfx_200",
            brand = FilmBrand.ILFORD,
            name = "SFX 200",
            iso = 200,
            category = FilmCategory.INFRARED,
            lutResId = R.raw.hald_rollei_ir400,
            lutType = LutType.PNG,
            grainAmount = 0.12f,
            grainSize = 1.3f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0f,
            contrast = 1.35f,
            shadowLift = 0f,
            accentColor = Color(0xFF8899AA),
            description = "Near-infrared: glowing foliage, black skies.",
        ),

        FilmStock(
            id = "fuji_pro400h",
            brand = FilmBrand.FUJI,
            name = "Pro 400H",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_pro400h,
            lutType = LutType.PNG,
            grainAmount = 0.09f,
            grainSize = 1.0f,
            lightLeakProbability = 0.06f,
            colorTempShift = -80,
            highlightRolloff = 0.68f,
            saturation = 0.88f,
            contrast = 0.80f,
            shadowLift = 18f,
            accentColor = Color(0xFF80B8D0),
            description = "Airy pastel portraits. The fashion studio standard.",
        ),

        FilmStock(
            id = "fuji_superia_400",
            brand = FilmBrand.FUJI,
            name = "Superia 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_superia400,
            lutType = LutType.PNG,
            grainAmount = 0.12f,
            grainSize = 1.2f,
            lightLeakProbability = 0.09f,
            colorTempShift = -120,
            highlightRolloff = 0.50f,
            saturation = 0.92f,
            contrast = 1.05f,
            shadowLift = 6f,
            accentColor = Color(0xFF4EAEDD),
            description = "Cool shadows, vivid highlights. Everyday versatility.",
        ),

        FilmStock(
            id = "fuji_neopan_400",
            brand = FilmBrand.FUJI,
            name = "Neopan 400",
            iso = 400,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = null,
            grainAmount = 0.15f,
            grainSize = 1.4f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.50f,
            saturation = 0f,
            contrast = 1.10f,
            shadowLift = 7f,
            accentColor = Color(0xFFAAAAAA),
            description = "Warm grays, smooth gradation. Japanese street soul.",
        ),

        FilmStock(
            id = "ilford_delta_400",
            brand = FilmBrand.ILFORD,
            name = "Delta 400",
            iso = 400,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_delta400,
            lutType = LutType.PNG,
            grainAmount = 0.11f,
            grainSize = 1.1f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.48f,
            saturation = 0f,
            contrast = 1.05f,
            shadowLift = 5f,
            accentColor = Color(0xFFB8B8B8),
            description = "The versatile Delta. Reportage with latitude.",
        ),

        FilmStock(
            id = "ilford_hp5",
            brand = FilmBrand.ILFORD,
            name = "HP5 Plus",
            iso = 400,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_hp5,
            lutType = LutType.PNG,
            grainAmount = 0.14f,
            grainSize = 1.3f,
            lightLeakProbability = 0.06f,
            colorTempShift = 0,
            highlightRolloff = 0.55f,
            saturation = 0f,
            contrast = 1.06f,
            shadowLift = 8f,
            accentColor = Color(0xFFB0B0B0),
            description = "Classic reportage grain. Push to 3200 in your mind.",
        ),

        FilmStock(
            id = "ilford_xp2",
            brand = FilmBrand.ILFORD,
            name = "XP2 Super",
            iso = 400,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_xp2,
            lutType = LutType.PNG,
            grainAmount = 0.08f,
            grainSize = 0.9f,
            lightLeakProbability = 0.06f,
            colorTempShift = 0,
            highlightRolloff = 0.52f,
            saturation = 0f,
            contrast = 0.98f,
            shadowLift = 9f,
            accentColor = Color(0xFFBBBBBB),
            description = "C-41 B&W. Lab-friendly, smooth grain at any exposure.",
        ),

        FilmStock(
            id = "kodak_portra_400",
            brand = FilmBrand.KODAK,
            name = "Portra 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_portra400,
            lutType = LutType.PNG,
            grainAmount = 0.10f,
            grainSize = 1.1f,
            lightLeakProbability = 0.07f,
            colorTempShift = +200,
            highlightRolloff = 0.65f,
            saturation = 0.85f,
            contrast = 0.82f,
            shadowLift = 20f,
            accentColor = Color(0xFFE8C87A),
            description = "Warm, flattering skin tones. The portrait standard.",
        ),

        FilmStock(
            id = "kodak_portra_400_nc",
            brand = FilmBrand.KODAK,
            name = "Portra 400 NC",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_portra400_nc,
            lutType = LutType.PNG,
            grainAmount = 0.09f,
            grainSize = 1.0f,
            lightLeakProbability = 0.06f,
            colorTempShift = +160,
            highlightRolloff = 0.68f,
            saturation = 0.80f,
            contrast = 0.78f,
            shadowLift = 22f,
            accentColor = Color(0xFFE8C870),
            description = "Natural Color — subtle palette, faithful skin tones.",
        ),

        FilmStock(
            id = "kodak_portra_400_uc",
            brand = FilmBrand.KODAK,
            name = "Portra 400 UC",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_portra400_uc,
            lutType = LutType.PNG,
            grainAmount = 0.10f,
            grainSize = 1.1f,
            lightLeakProbability = 0.07f,
            colorTempShift = +240,
            highlightRolloff = 0.60f,
            saturation = 1.02f,
            contrast = 0.88f,
            shadowLift = 16f,
            accentColor = Color(0xFFE87A30),
            description = "Ultra Color — vibrant, punchy, push-processing style.",
        ),

        FilmStock(
            id = "kodak_portra_400_vc",
            brand = FilmBrand.KODAK,
            name = "Portra 400 VC",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_portra400_vc,
            lutType = LutType.PNG,
            grainAmount = 0.10f,
            grainSize = 1.1f,
            lightLeakProbability = 0.07f,
            colorTempShift = +200,
            highlightRolloff = 0.62f,
            saturation = 0.95f,
            contrast = 0.86f,
            shadowLift = 18f,
            accentColor = Color(0xFFE89050),
            description = "Vivid Color — richer tones with portrait softness.",
        ),

        FilmStock(
            id = "kodak_tmax_400",
            brand = FilmBrand.KODAK,
            name = "T-MAX 400",
            iso = 400,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_kodak_tmax400,
            lutType = LutType.PNG,
            grainAmount = 0.08f,
            grainSize = 0.8f,
            lightLeakProbability = 0.04f,
            colorTempShift = 0,
            highlightRolloff = 0.42f,
            saturation = 0f,
            contrast = 1.05f,
            shadowLift = 4f,
            accentColor = Color(0xFFCCCCCC),
            description = "The flexible B&W standard. Speed with precision.",
        ),

        FilmStock(
            id = "kodak_trix_400",
            brand = FilmBrand.KODAK,
            name = "Tri-X 400",
            iso = 400,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_kodak_trix400,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.8f,
            lightLeakProbability = 0.06f,
            colorTempShift = 0,
            highlightRolloff = 0.58f,
            saturation = 0f,
            contrast = 1.22f,
            shadowLift = 0f,
            accentColor = Color(0xFF909090),
            description = "Gritty grain, deep blacks. Street photography icon.",
        ),

        FilmStock(
            id = "kodak_ultramax_400",
            brand = FilmBrand.KODAK,
            name = "Ultramax 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = null,
            grainAmount = 0.13f,
            grainSize = 1.3f,
            lightLeakProbability = 0.09f,
            colorTempShift = +180,
            highlightRolloff = 0.50f,
            saturation = 1.10f,
            contrast = 0.95f,
            shadowLift = 10f,
            accentColor = Color(0xFFE8A040),
            description = "Warm grain, every situation. The tourist's choice.",
        ),

        FilmStock(
            id = "lomo_chrome_metropolis",
            brand = FilmBrand.LOMOGRAPHY,
            name = "LomoChrome Metropolis",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = null,
            grainAmount = 0.16f,
            grainSize = 1.4f,
            lightLeakProbability = 0.15f,
            colorTempShift = -60,
            highlightRolloff = 0.45f,
            saturation = 0.72f,
            contrast = 1.14f,
            shadowLift = 10f,
            accentColor = Color(0xFF8A9A6A),
            description = "Urban decay. Muted tones, olive shadows.",
        ),

        FilmStock(
            id = "lomo_chrome_purple",
            brand = FilmBrand.LOMOGRAPHY,
            name = "LomoChrome Purple",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_lomo_chrome_purple,
            grainAmount = 0.18f,
            grainSize = 1.6f,
            lightLeakProbability = 0.22f,
            colorTempShift = -200,
            highlightRolloff = 0.42f,
            saturation = 1.45f,
            contrast = 1.12f,
            shadowLift = 5f,
            accentColor = Color(0xFFB06ABF),
            description = "Greens become purple. Reality optional.",
        ),

        FilmStock(
            id = "rollei_ir_400",
            brand = FilmBrand.ROLLEI,
            name = "Infrared 400",
            iso = 400,
            category = FilmCategory.INFRARED,
            lutResId = R.raw.hald_rollei_ir400,
            lutType = LutType.PNG,
            grainAmount = 0.16f,
            grainSize = 1.5f,
            lightLeakProbability = 0.08f,
            colorTempShift = 0,
            highlightRolloff = 0.42f,
            saturation = 0f,
            contrast = 1.40f,
            shadowLift = 0f,
            accentColor = Color(0xFF556677),
            description = "Infrared B&W. White foliage, black skies, drama.",
        ),

        FilmStock(
            id = "fuji_800z",
            brand = FilmBrand.FUJI,
            name = "800Z",
            iso = 800,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_800z,
            lutType = LutType.PNG,
            grainAmount = 0.18f,
            grainSize = 1.5f,
            lightLeakProbability = 0.10f,
            colorTempShift = +150,
            highlightRolloff = 0.52f,
            saturation = 0.95f,
            contrast = 1.05f,
            shadowLift = 10f,
            accentColor = Color(0xFF70A8C8),
            description = "High-speed warmth. Events and dim rooms.",
        ),

        FilmStock(
            id = "fuji_superia_800",
            brand = FilmBrand.FUJI,
            name = "Superia 800",
            iso = 800,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_superia800,
            lutType = LutType.PNG,
            grainAmount = 0.18f,
            grainSize = 1.6f,
            lightLeakProbability = 0.10f,
            colorTempShift = -60,
            highlightRolloff = 0.48f,
            saturation = 0.95f,
            contrast = 1.08f,
            shadowLift = 8f,
            accentColor = Color(0xFF4488CC),
            description = "Fast consumer film. Cool shadows, warm highlights.",
        ),

        FilmStock(
            id = "cinestill_800t",
            brand = FilmBrand.CINESTILL,
            name = "800T",
            iso = 800,
            category = FilmCategory.COLOR,
            lutResId = null,
            grainAmount = 0.22f,
            grainSize = 1.7f,
            lightLeakProbability = 0.18f,
            colorTempShift = -900,
            highlightRolloff = 0.60f,
            saturation = 1.08f,
            contrast = 1.14f,
            shadowLift = 16f,
            accentColor = Color(0xFFCC3344),
            description = "Cinema grain, halation glow. Neon nights.",
        ),

        FilmStock(
            id = "ilford_hps_800",
            brand = FilmBrand.ILFORD,
            name = "HPS 800",
            iso = 800,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_ilford_hps800,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.7f,
            lightLeakProbability = 0.06f,
            colorTempShift = 0,
            highlightRolloff = 0.55f,
            saturation = 0f,
            contrast = 1.15f,
            shadowLift = 3f,
            accentColor = Color(0xFF999999),
            description = "Discontinued speed legend. High grain, strong character.",
        ),

        FilmStock(
            id = "kodak_portra_800",
            brand = FilmBrand.KODAK,
            name = "Portra 800",
            iso = 800,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_kodak_portra800,
            lutType = LutType.PNG,
            grainAmount = 0.16f,
            grainSize = 1.4f,
            lightLeakProbability = 0.09f,
            colorTempShift = +280,
            highlightRolloff = 0.60f,
            saturation = 0.88f,
            contrast = 0.85f,
            shadowLift = 18f,
            accentColor = Color(0xFFD4A840),
            description = "Available-light portrait. Warm and a little gritty.",
        ),

        FilmStock(
            id = "polaroid_667",
            brand = FilmBrand.POLAROID,
            name = "667",
            iso = 800,
            category = FilmCategory.INSTANT,
            isBlackAndWhite = true,
            lutResId = R.raw.hald_polaroid_667,
            lutType = LutType.PNG,
            grainAmount = 0.22f,
            grainSize = 2.0f,
            lightLeakProbability = 0.25f,
            colorTempShift = 0,
            highlightRolloff = 0.58f,
            saturation = 0f,
            contrast = 1.12f,
            shadowLift = 10f,
            accentColor = Color(0xFF888888),
            description = "Coaterless high-speed B&W pack film. Raw and immediate.",
        ),

        FilmStock(
            id = "fuji_superia_1600",
            brand = FilmBrand.FUJI,
            name = "Superia 1600",
            iso = 1600,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_superia1600,
            lutType = LutType.PNG,
            grainAmount = 0.24f,
            grainSize = 1.8f,
            lightLeakProbability = 0.11f,
            colorTempShift = -80,
            highlightRolloff = 0.50f,
            saturation = 0.88f,
            contrast = 1.12f,
            shadowLift = 6f,
            accentColor = Color(0xFF3377BB),
            description = "Low light in cool tones. Grain tells the story.",
        ),

        FilmStock(
            id = "fuji_natura_1600",
            brand = FilmBrand.FUJI,
            name = "Natura 1600",
            iso = 1600,
            category = FilmCategory.COLOR,
            lutResId = R.raw.hald_fuji_superia1600,
            lutType = LutType.PNG,
            grainAmount = 0.26f,
            grainSize = 1.9f,
            lightLeakProbability = 0.12f,
            colorTempShift = +120,
            highlightRolloff = 0.55f,
            saturation = 0.90f,
            contrast = 1.10f,
            shadowLift = 12f,
            accentColor = Color(0xFFCCA060),
            description = "Available-light grain. Warm, alive, imperfect.",
        ),

        FilmStock(
            id = "fuji_neopan_1600",
            brand = FilmBrand.FUJI,
            name = "Neopan 1600",
            iso = 1600,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_fuji_neopan1600,
            lutType = LutType.PNG,
            grainAmount = 0.25f,
            grainSize = 1.9f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.60f,
            saturation = 0f,
            contrast = 1.20f,
            shadowLift = 0f,
            accentColor = Color(0xFF888888),
            description = "Pushed-to-the-limit B&W. Grain and shadow.",
        ),

        FilmStock(
            id = "ilford_delta_3200",
            brand = FilmBrand.ILFORD,
            name = "Delta 3200",
            iso = 3200,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_ilford_delta3200,
            grainAmount = 0.28f,
            grainSize = 2.0f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.68f,
            saturation = 0f,
            contrast = 1.28f,
            shadowLift = 0f,
            accentColor = Color(0xFF787878),
            description = "Extreme grain, dramatic shadows. Low light legend.",
        ),

        FilmStock(
            id = "kodak_tmax_3200",
            brand = FilmBrand.KODAK,
            name = "T-MAX 3200",
            iso = 3200,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.hald_kodak_tmax3200,
            lutType = LutType.PNG,
            grainAmount = 0.30f,
            grainSize = 2.2f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.65f,
            saturation = 0f,
            contrast = 1.30f,
            shadowLift = 0f,
            accentColor = Color(0xFF686868),
            description = "Nighttime B&W. Extreme grain, deep blacks.",
        ),

        FilmStock(
            id = "polaroid_665",
            brand = FilmBrand.POLAROID,
            name = "665",
            iso = 75,
            category = FilmCategory.INSTANT,
            isBlackAndWhite = true,
            lutResId = R.raw.hald_polaroid_665,
            lutType = LutType.PNG,
            grainAmount = 0.20f,
            grainSize = 1.8f,
            lightLeakProbability = 0.25f,
            colorTempShift = 0,
            highlightRolloff = 0.52f,
            saturation = 0f,
            contrast = 0.92f,
            shadowLift = 12f,
            accentColor = Color(0xFFBBAA99),
            description = "Positive/negative pack film. Archival B&W prints.",
        ),

    ).sortedWith(compareBy({ it.iso }, { it.name }))

    val default: FilmStock get() = all.first { it.id == "kodak_portra_400" }

    fun findById(id: String): FilmStock? = all.firstOrNull { it.id == id }

    fun byBrand(brand: FilmBrand): List<FilmStock> = all.filter { it.brand == brand }

    fun byCategory(category: FilmCategory): List<FilmStock> = all.filter { it.category == category }
}
