package com.jegly.filmcamera.film

import androidx.compose.ui.graphics.Color
import com.jegly.filmcamera.R

internal val stocksRollei: List<FilmStock> = listOf(
        FilmStock(
            id = "bw_rollei_retro_80s",
            brand = FilmBrand.ROLLEI,
            name = "Rollei Retro 80S",
            iso = 80,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_rollei_retro_80s,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Rollei Retro 80S",
        ),
        FilmStock(
            id = "bw_rollei_retro_100_tonal",
            brand = FilmBrand.ROLLEI,
            name = "Rollei Retro 100 Tonal",
            iso = 100,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_rollei_retro_100_tonal,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Rollei Retro 100 Tonal",
        ),
        FilmStock(
            id = "bw_rollei_ir_400",
            brand = FilmBrand.ROLLEI,
            name = "Rollei Ir 400",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.INFRARED,
            lutResId = R.raw.lut_bw_rollei_ir_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Rollei Ir 400",
        ),
        FilmStock(
            id = "bw_rollei_ortho_25",
            brand = FilmBrand.ROLLEI,
            name = "Rollei Ortho 25",
            iso = 25,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_rollei_ortho_25,
            lutType = LutType.CUBE,
            grainAmount = 0.04f,
            grainSize = 1.01f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Rollei Ortho 25",
        ),
)
