package com.jegly.filmcamera.film

import androidx.compose.ui.graphics.Color
import com.jegly.filmcamera.R

internal val stocksFuji: List<FilmStock> = listOf(
        FilmStock(
            id = "print_fuji_3513_constlclip",
            brand = FilmBrand.FUJI,
            name = "Fuji 3513 Constlclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_fuji_3513_constlclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 3513 Constlclip",
        ),
        FilmStock(
            id = "print_fuji_3513_cuspclip",
            brand = FilmBrand.FUJI,
            name = "Fuji 3513 Cuspclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_fuji_3513_cuspclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 3513 Cuspclip",
        ),
        FilmStock(
            id = "print_fuji_3510_constlmap",
            brand = FilmBrand.FUJI,
            name = "Fuji 3510 Constlmap",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_fuji_3510_constlmap,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 3510 Constlmap",
        ),
        FilmStock(
            id = "print_fuji_3510_constlclip",
            brand = FilmBrand.FUJI,
            name = "Fuji 3510 Constlclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_fuji_3510_constlclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 3510 Constlclip",
        ),
        FilmStock(
            id = "print_fuji_3510_cuspclip",
            brand = FilmBrand.FUJI,
            name = "Fuji 3510 Cuspclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_fuji_3510_cuspclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 3510 Cuspclip",
        ),
        FilmStock(
            id = "print_fuji_3513_constlmap",
            brand = FilmBrand.FUJI,
            name = "Fuji 3513 Constlmap",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_fuji_3513_constlmap,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 3513 Constlmap",
        ),
        FilmStock(
            id = "negative_old_fuji_neopan_1600",
            brand = FilmBrand.FUJI,
            name = "Fuji Neopan 1600 ++",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_neopan_1600_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Neopan 1600 ++",
        ),
        FilmStock(
            id = "negative_old_fuji_neopan_1600_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Neopan 1600 +",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_neopan_1600_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Neopan 1600 +",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_800",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 800 ++",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_800_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 800 ++",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_100",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 100 -",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_100_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 100 -",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_1600",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 1600 +",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_1600_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 1600 +",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_400",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 400 ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_400_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 400 ++",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_800_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 800 -",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_800_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 800 -",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_100_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 100 ++",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_100_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 100 ++",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_400_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 400 -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_400_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 400 -",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_800_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 800",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_800,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 800",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_100_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 100 +",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_100_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 100 +",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_1600_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 1600 -",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_1600_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 1600 -",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_1600_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 1600",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_1600,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 1600",
        ),
        FilmStock(
            id = "negative_old_fuji_neopan_1600_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Neopan 1600",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_neopan_1600,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Neopan 1600",
        ),
        FilmStock(
            id = "negative_old_fuji_neopan_1600_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Neopan 1600 -",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_neopan_1600_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Neopan 1600 -",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_800_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 800 +",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_800_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 800 +",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_400_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 400",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_400_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 400 +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_400_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 400 +",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_1600_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 1600 ++",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_1600_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 1600 ++",
        ),
        FilmStock(
            id = "negative_old_fuji_superia_100_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_fuji_superia_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 100",
        ),
        FilmStock(
            id = "negative_new_fuji_160c",
            brand = FilmBrand.FUJI,
            name = "Fuji 160C",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_160c,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 160C",
        ),
        FilmStock(
            id = "negative_new_fuji_160c_2",
            brand = FilmBrand.FUJI,
            name = "Fuji 160C -",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_160c_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 160C -",
        ),
        FilmStock(
            id = "negative_new_fuji_800z",
            brand = FilmBrand.FUJI,
            name = "Fuji 800Z -",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_800z_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 800Z -",
        ),
        FilmStock(
            id = "negative_new_fuji_400h",
            brand = FilmBrand.FUJI,
            name = "Fuji 400H ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_400h_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 400H ++",
        ),
        FilmStock(
            id = "negative_new_fuji_160c_3",
            brand = FilmBrand.FUJI,
            name = "Fuji 160C +",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_160c_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 160C +",
        ),
        FilmStock(
            id = "negative_new_fuji_400h_2",
            brand = FilmBrand.FUJI,
            name = "Fuji 400H -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_400h_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 400H -",
        ),
        FilmStock(
            id = "negative_new_fuji_800z_2",
            brand = FilmBrand.FUJI,
            name = "Fuji 800Z +",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_800z_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 800Z +",
        ),
        FilmStock(
            id = "negative_new_fuji_160c_4",
            brand = FilmBrand.FUJI,
            name = "Fuji 160C ++",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_160c_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 160C ++",
        ),
        FilmStock(
            id = "negative_new_fuji_800z_3",
            brand = FilmBrand.FUJI,
            name = "Fuji 800Z",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_800z,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 800Z",
        ),
        FilmStock(
            id = "negative_new_fuji_400h_3",
            brand = FilmBrand.FUJI,
            name = "Fuji 400H",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_400h,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 400H",
        ),
        FilmStock(
            id = "negative_new_fuji_800z_4",
            brand = FilmBrand.FUJI,
            name = "Fuji 800Z ++",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_800z_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 800Z ++",
        ),
        FilmStock(
            id = "negative_new_fuji_400h_4",
            brand = FilmBrand.FUJI,
            name = "Fuji 400H +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_fuji_400h_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji 400H +",
        ),
        FilmStock(
            id = "bw_fuji_neopan_acros_100",
            brand = FilmBrand.FUJI,
            name = "Fuji Neopan Acros 100",
            iso = 100,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_fuji_neopan_acros_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Neopan Acros 100",
        ),
        FilmStock(
            id = "bw_fuji_neopan_1600",
            brand = FilmBrand.FUJI,
            name = "Fuji Neopan 1600",
            iso = 160,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_fuji_neopan_1600,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Neopan 1600",
        ),
        FilmStock(
            id = "colorslide_fuji_provia_400f",
            brand = FilmBrand.FUJI,
            name = "Fuji Provia 400F",
            iso = 400,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_provia_400f,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Provia 400F",
        ),
        FilmStock(
            id = "colorslide_fuji_astia_100f",
            brand = FilmBrand.FUJI,
            name = "Fuji Astia 100F",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_astia_100f,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Astia 100F",
        ),
        FilmStock(
            id = "colorslide_fuji_provia_100_generic",
            brand = FilmBrand.FUJI,
            name = "Fuji Provia 100 Generic",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_provia_100_generic,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Provia 100 Generic",
        ),
        FilmStock(
            id = "colorslide_fuji_fp_100c",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp 100C",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_fp_100c,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp 100C",
        ),
        FilmStock(
            id = "colorslide_fuji_sensia_100",
            brand = FilmBrand.FUJI,
            name = "Fuji Sensia 100",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_sensia_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Sensia 100",
        ),
        FilmStock(
            id = "colorslide_fuji_provia_100f",
            brand = FilmBrand.FUJI,
            name = "Fuji Provia 100F",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_provia_100f,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Provia 100F",
        ),
        FilmStock(
            id = "colorslide_fuji_provia_400x",
            brand = FilmBrand.FUJI,
            name = "Fuji Provia 400X",
            iso = 400,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_provia_400x,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Provia 400X",
        ),
        FilmStock(
            id = "colorslide_fuji_velvia_100_generic",
            brand = FilmBrand.FUJI,
            name = "Fuji Velvia 100 Generic",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_velvia_100_generic,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Velvia 100 Generic",
        ),
        FilmStock(
            id = "colorslide_fuji_velvia_50",
            brand = FilmBrand.FUJI,
            name = "Fuji Velvia 50",
            iso = 50,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_velvia_50,
            lutType = LutType.CUBE,
            grainAmount = 0.04f,
            grainSize = 1.02f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Velvia 50",
        ),
        FilmStock(
            id = "colorslide_fuji_astia_100_generic",
            brand = FilmBrand.FUJI,
            name = "Fuji Astia 100 Generic",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_fuji_astia_100_generic,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Astia 100 Generic",
        ),
        FilmStock(
            id = "colorslide_fuji_superia_200_xpro",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 200 Xpro",
            iso = 200,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.lut_colorslide_fuji_superia_200_xpro,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 200 Xpro",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_sepia",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Sepia",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_sepia,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Sepia",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_pro_neg_std",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Pro Neg Std",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_pro_neg_std,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Xtrans Iii Pro Neg Std",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_acros_r",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Acros+R",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_acros_pr,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Acros+R",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_velvia",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Velvia",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_velvia,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Xtrans Iii Velvia",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_classic_chrome",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Classic Chrome",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_classic_chrome,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Xtrans Iii Classic Chrome",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_acros",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Acros",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_acros,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Acros",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_acros_ye",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Acros+Ye",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_acros_pye,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Acros+Ye",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_mono",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Mono",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_mono,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Mono",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_mono_g",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Mono+G",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_mono_pg,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Mono+G",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_pro_neg_hi",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Pro Neg Hi",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_pro_neg_hi,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Xtrans Iii Pro Neg Hi",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_provia",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Provia",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_provia,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Xtrans Iii Provia",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_astia",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Astia",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_astia,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Xtrans Iii Astia",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_mono_ye",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Mono+Ye",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_mono_pye,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Mono+Ye",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_mono_r",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Mono+R",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_mono_pr,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Mono+R",
        ),
        FilmStock(
            id = "fujixtransiii_fuji_xtrans_iii_acros_g",
            brand = FilmBrand.FUJI,
            name = "Fuji Xtrans Iii Acros+G",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_fujixtransiii_fuji_xtrans_iii_acros_pg,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Fuji Xtrans Iii Acros+G",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative -",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_hc",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Hc",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_hc,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Hc",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C +",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C +",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_cool",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Cool +",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_cool_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Cool +",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative +",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_alt",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C ++ Alt",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_pp_alt,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C ++ Alt",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_cool_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Cool ++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_cool_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Cool ++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C --",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C --",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_cool_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Cool --",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_cool_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Cool --",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative --",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B --",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C ++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C ++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B -",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative_5",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative +++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative +++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative +",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative +",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B ++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_cool_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Cool",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_cool,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Cool",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative_3",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative +++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative +++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_5",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C -",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C -",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B +",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative_4",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative -",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative -",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_6",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C +++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C +++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative_5",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative ++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative ++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative_6",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative --",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative --",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_5",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_negative_alt",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Negative ++ Alt",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_negative_pp_alt,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Negative ++ Alt",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative_early",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative Early",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative_early,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative Early",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_cool_5",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Cool -",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_cool_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Cool -",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_6",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B +++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B +++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_3000b_negative_6",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-3000B Negative ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m3000b_negative_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-3000B Negative ++",
        ),
        FilmStock(
            id = "instant_pro_fuji_fp_100c_alt_2",
            brand = FilmBrand.FUJI,
            name = "Fuji Fp-100C Alt",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_fuji_fp_m100c_alt,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Fp-100C Alt",
        ),
        FilmStock(
            id = "negative_color_fuji_superia_x_tra_800",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia X-Tra 800",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_fuji_superia_x_mtra_800,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia X-Tra 800",
        ),
        FilmStock(
            id = "negative_color_fuji_superia_200",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_fuji_superia_200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia 200",
        ),
        FilmStock(
            id = "negative_color_fuji_superia_reala_100",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia Reala 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_fuji_superia_reala_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia Reala 100",
        ),
        FilmStock(
            id = "negative_color_fuji_superia_hg_1600",
            brand = FilmBrand.FUJI,
            name = "Fuji Superia Hg 1600",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_fuji_superia_hg_1600,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF5AAEDC),
            description = "Fuji Superia Hg 1600",
        ),
)
