package com.jegly.filmcamera.film

import androidx.compose.ui.graphics.Color
import com.jegly.filmcamera.R

internal val stocksPolaroid: List<FilmStock> = listOf(
        FilmStock(
            id = "bw_polaroid_672",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 672",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_polaroid_672,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Polaroid 672",
        ),
        FilmStock(
            id = "bw_polaroid_667",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 667",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_polaroid_667,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Polaroid 667",
        ),
        FilmStock(
            id = "bw_polaroid_664",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 664",
            iso = 64,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_polaroid_664,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Polaroid 664",
        ),
        FilmStock(
            id = "colorslide_polaroid_669",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669",
            iso = 400,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_polaroid_669,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669",
        ),
        FilmStock(
            id = "colorslide_polaroid_polachrome",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Polachrome",
            iso = 400,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_polaroid_polachrome,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Polachrome",
        ),
        FilmStock(
            id = "colorslide_polaroid_690",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690",
            iso = 400,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_polaroid_690,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 --",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 ++",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_cold",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Cold ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_cold_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Cold ++",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_cold_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Cold --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_cold_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Cold --",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_warm",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Warm --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_warm_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Warm --",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_negative",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 Negative +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_negative_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 Negative +",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_cold",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 Cold -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_cold_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 Cold -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_negative_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 Negative",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_negative,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 Negative",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 --",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 +",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 +++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 +++",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 ++",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_warm_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Warm +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_warm_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Warm +",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_cold_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 Cold --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_cold_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 Cold --",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 +",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_cold_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Cold -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_cold_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Cold -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_cold_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 Cold",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_cold,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 Cold",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_cold_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Cold",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_cold,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Cold",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 --",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_warm_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Warm -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_warm_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Warm -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_negative_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 Negative -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_negative_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 Negative -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_cold_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Cold +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_cold_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Cold +",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 -",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_warm_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Warm ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_warm_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Warm ++",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_cold_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 Cold +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_cold_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 Cold +",
        ),
        FilmStock(
            id = "instant_pro_polaroid_690_warm_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 690 Warm",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_690_warm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 690 Warm",
        ),
        FilmStock(
            id = "instant_pro_polaroid_665_negative_hc",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 665 Negative Hc",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_665_negative_hc,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 665 Negative Hc",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 ++",
        ),
        FilmStock(
            id = "instant_pro_polaroid_669_6",
            brand = FilmBrand.POLAROID,
            name = "Polaroid 669 +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_pro_polaroid_669_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid 669 +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_cold",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Cold -",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_cold_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Cold -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 -",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_cold",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Cold -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_cold_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Cold -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_warm",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Warm ++",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_warm_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Warm ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_cold_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Cold +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_cold_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Cold +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_cold_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Cold ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_cold_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Cold ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_cold_alt",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Cold ++ Alt",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_cold_pp_alt,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Cold ++ Alt",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_warm",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Warm -",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_warm_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Warm -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 ++",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_cold",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Cold",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_cold,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Cold",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_cold_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Cold --",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_cold_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Cold --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired ---",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_mmm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired ---",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_warm_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Warm --",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_warm_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Warm --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_cold_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Cold -",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_cold_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Cold -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_cold_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Cold +",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_cold_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Cold +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 +",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_warm_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Warm +++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_warm_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Warm +++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_warm",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Warm -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_warm_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Warm -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_cold",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired Cold ---",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_cold_mmm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired Cold ---",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_warm_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Warm",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_warm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Warm",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_cold_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Cold +++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_cold_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Cold +++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_warm_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Warm --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_warm_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Warm --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_warm_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Warm",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_warm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Warm",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_cold_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired Cold",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_cold,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired Cold",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_2",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_cold_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Cold +",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_cold_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Cold +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_warm_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Warm --",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_warm_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Warm --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_cold_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired Cold -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_cold_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired Cold -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_warm_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Warm ++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_warm_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Warm ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_warm_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Warm +",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_warm_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Warm +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 +++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_ppp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 +++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_warm_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Warm -",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_warm_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Warm -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_warm_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Warm ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_warm_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Warm ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_cold_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Cold",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_cold,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Cold",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_warm_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Warm +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_warm_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Warm +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_cold_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired Cold --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_cold_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired Cold --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_cold_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 Cold --",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_cold_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 Cold --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_cold_3",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Cold",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_cold,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Cold",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 ++",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 --",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_70_6",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-70 -",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m70_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-70 -",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_warm_6",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Warm +",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_warm_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Warm +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_cold_4",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Cold --",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_cold_mm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Cold --",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_cold_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Cold ++",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_cold_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Cold ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_time_zero_expired_6",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Time Zero Expired +",
            iso = 400,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_time_zero_expired_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Time Zero Expired +",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_100uv_cold_6",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-100Uv+ Cold ++",
            iso = 100,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m100uv_p_cold_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-100Uv+ Cold ++",
        ),
        FilmStock(
            id = "instant_consumer_polaroid_px_680_warm_5",
            brand = FilmBrand.POLAROID,
            name = "Polaroid Px-680 Warm",
            iso = 80,
            category = FilmCategory.INSTANT,
            lutResId = R.raw.lut_instant_consumer_polaroid_px_m680_warm,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.22f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 18.0f,
            accentColor = Color(0xFFDDAA77),
            description = "Polaroid Px-680 Warm",
        ),
)
