package com.jegly.filmcamera.film

import androidx.compose.ui.graphics.Color
import com.jegly.filmcamera.R

internal val stocksAgfa: List<FilmStock> = listOf(
        FilmStock(
            id = "bw_agfa_apx_25",
            brand = FilmBrand.AGFA,
            name = "Agfa Apx 25",
            iso = 25,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_agfa_apx_25,
            lutType = LutType.CUBE,
            grainAmount = 0.04f,
            grainSize = 1.01f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Agfa Apx 25",
        ),
        FilmStock(
            id = "bw_agfa_apx_100",
            brand = FilmBrand.AGFA,
            name = "Agfa Apx 100",
            iso = 100,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_agfa_apx_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Agfa Apx 100",
        ),
        FilmStock(
            id = "colorslide_agfa_precisa_100",
            brand = FilmBrand.AGFA,
            name = "Agfa Precisa 100",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_agfa_precisa_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF40CC80),
            description = "Agfa Precisa 100",
        ),
        FilmStock(
            id = "negative_color_agfa_vista_200",
            brand = FilmBrand.AGFA,
            name = "Agfa Vista 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_agfa_vista_200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF40CC80),
            description = "Agfa Vista 200",
        ),
        FilmStock(
            id = "negative_color_agfa_ultra_color_100",
            brand = FilmBrand.AGFA,
            name = "Agfa Ultra Color 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_agfa_ultra_color_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFF40CC80),
            description = "Agfa Ultra Color 100",
        ),
)
