package com.jegly.filmcamera.film

import androidx.compose.ui.graphics.Color
import com.jegly.filmcamera.R

internal val stocksIlford: List<FilmStock> = listOf(
        FilmStock(
            id = "negative_old_ilford_delta_3200",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 3200 ++",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_ilford_delta_3200_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 3200 ++",
        ),
        FilmStock(
            id = "negative_old_ilford_delta_3200_2",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 3200 +",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_ilford_delta_3200_p,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 3200 +",
        ),
        FilmStock(
            id = "negative_old_ilford_delta_3200_3",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 3200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_ilford_delta_3200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 3200",
        ),
        FilmStock(
            id = "negative_old_ilford_delta_3200_4",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 3200 -",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_ilford_delta_3200_m,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 3200 -",
        ),
        FilmStock(
            id = "negative_new_ilford_hp_5",
            brand = FilmBrand.ILFORD,
            name = "Ilford Hp 5",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_ilford_hp_5,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Hp 5",
        ),
        FilmStock(
            id = "negative_new_ilford_hp_5_2",
            brand = FilmBrand.ILFORD,
            name = "Ilford Hp 5 +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_ilford_hp_5_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Hp 5 +",
        ),
        FilmStock(
            id = "negative_new_ilford_hp_5_3",
            brand = FilmBrand.ILFORD,
            name = "Ilford Hp 5 -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_ilford_hp_5_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Hp 5 -",
        ),
        FilmStock(
            id = "negative_new_ilford_hp_5_4",
            brand = FilmBrand.ILFORD,
            name = "Ilford Hp 5 ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_ilford_hp_5_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Hp 5 ++",
        ),
        FilmStock(
            id = "bw_ilford_hp_5_plus_400",
            brand = FilmBrand.ILFORD,
            name = "Ilford Hp 5 Plus 400",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_hp_5_plus_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Hp 5 Plus 400",
        ),
        FilmStock(
            id = "bw_ilford_hps_800",
            brand = FilmBrand.ILFORD,
            name = "Ilford Hps 800",
            iso = 80,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_hps_800,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Hps 800",
        ),
        FilmStock(
            id = "bw_ilford_xp_2",
            brand = FilmBrand.ILFORD,
            name = "Ilford Xp 2",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_xp_2,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Xp 2",
        ),
        FilmStock(
            id = "bw_ilford_fp_4_plus_125",
            brand = FilmBrand.ILFORD,
            name = "Ilford Fp 4 Plus 125",
            iso = 25,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_fp_4_plus_125,
            lutType = LutType.CUBE,
            grainAmount = 0.04f,
            grainSize = 1.01f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Fp 4 Plus 125",
        ),
        FilmStock(
            id = "bw_ilford_delta_3200",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 3200",
            iso = 200,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_delta_3200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 3200",
        ),
        FilmStock(
            id = "bw_ilford_delta_400",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 400",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_delta_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 400",
        ),
        FilmStock(
            id = "bw_ilford_delta_100",
            brand = FilmBrand.ILFORD,
            name = "Ilford Delta 100",
            iso = 100,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_delta_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Delta 100",
        ),
        FilmStock(
            id = "bw_ilford_pan_f_plus_50",
            brand = FilmBrand.ILFORD,
            name = "Ilford Pan F Plus 50",
            iso = 50,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_ilford_pan_f_plus_50,
            lutType = LutType.CUBE,
            grainAmount = 0.04f,
            grainSize = 1.02f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Ilford Pan F Plus 50",
        ),
)
