package com.jegly.filmcamera.film

import androidx.compose.ui.graphics.Color
import com.jegly.filmcamera.R

internal val stocksKodak: List<FilmStock> = listOf(
        FilmStock(
            id = "print_kodak_2393_cuspclip",
            brand = FilmBrand.KODAK,
            name = "Kodak 2393 Cuspclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_kodak_2393_cuspclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak 2393 Cuspclip",
        ),
        FilmStock(
            id = "print_kodak_2383_constlmap",
            brand = FilmBrand.KODAK,
            name = "Kodak 2383 Constlmap",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_kodak_2383_constlmap,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak 2383 Constlmap",
        ),
        FilmStock(
            id = "print_kodak_2383_constlclip",
            brand = FilmBrand.KODAK,
            name = "Kodak 2383 Constlclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_kodak_2383_constlclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak 2383 Constlclip",
        ),
        FilmStock(
            id = "print_kodak_2383_cuspclip",
            brand = FilmBrand.KODAK,
            name = "Kodak 2383 Cuspclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_kodak_2383_cuspclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak 2383 Cuspclip",
        ),
        FilmStock(
            id = "print_kodak_2393_constlclip",
            brand = FilmBrand.KODAK,
            name = "Kodak 2393 Constlclip",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_kodak_2393_constlclip,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak 2393 Constlclip",
        ),
        FilmStock(
            id = "print_kodak_2393_constlmap",
            brand = FilmBrand.KODAK,
            name = "Kodak 2393 Constlmap",
            iso = 400,
            category = FilmCategory.PRINT,
            lutResId = R.raw.lut_print_kodak_2393_constlmap,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.00f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak 2393 Constlmap",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_nc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Nc",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_nc,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Nc",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_vc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Vc",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_vc,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Vc",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_vc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Vc -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_vc_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Vc -",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_vc_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Vc ++",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_vc_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Vc ++",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_nc_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Nc -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_nc_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Nc -",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_nc_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Nc ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_nc_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Nc ++",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_nc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Nc -",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_nc_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Nc -",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_vc_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Vc -",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_vc_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Vc -",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_nc_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Nc ++",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_nc_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Nc ++",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_vc_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Vc +",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_vc_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Vc +",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_vc_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Vc ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_vc_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Vc ++",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_vc_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Vc",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_vc,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Vc",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_nc_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Nc +",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_nc_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Nc +",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_vc_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Vc +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_vc_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Vc +",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_uc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Uc +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_uc_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Uc +",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_uc_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Uc ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_uc_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Uc ++",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_uc_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Uc -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_uc_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Uc -",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_160_nc_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Nc",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_160_nc,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Nc",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_uc_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Uc",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_uc,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Uc",
        ),
        FilmStock(
            id = "negative_old_kodak_portra_400_nc_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 Nc +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_old_kodak_portra_400_nc_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 Nc +",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_800",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 800 +",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_800_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 800 +",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_400",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_400_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 +",
        ),
        FilmStock(
            id = "negative_new_kodak_tmax_3200",
            brand = FilmBrand.KODAK,
            name = "Kodak Tmax 3200 +",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tmax_3200_p,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tmax 3200 +",
        ),
        FilmStock(
            id = "negative_new_kodak_tmax_3200_alt",
            brand = FilmBrand.KODAK,
            name = "Kodak Tmax 3200 Alt",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tmax_3200_alt,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tmax 3200 Alt",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_400_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_400_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 ++",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_400_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400 -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_400_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400 -",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_800_hc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 800 Hc",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_800_hc,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 800 Hc",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_800_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 800 ++",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_800_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 800 ++",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_160",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 +",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_160_p,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 +",
        ),
        FilmStock(
            id = "negative_new_kodak_tri_x_400",
            brand = FilmBrand.KODAK,
            name = "Kodak Tri-X 400 ++",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tri_mx_400_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tri-X 400 ++",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_160_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_160,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160",
        ),
        FilmStock(
            id = "negative_new_kodak_tri_x_400_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Tri-X 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tri_mx_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tri-X 400",
        ),
        FilmStock(
            id = "negative_new_kodak_tmax_3200_2",
            brand = FilmBrand.KODAK,
            name = "Kodak Tmax 3200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tmax_3200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tmax 3200",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_800_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 800 -",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_800_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 800 -",
        ),
        FilmStock(
            id = "negative_new_kodak_tri_x_400_alt",
            brand = FilmBrand.KODAK,
            name = "Kodak Tri-X 400 Alt",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tri_mx_400_alt,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tri-X 400 Alt",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_400_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 400",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_800_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 800",
            iso = 80,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_800,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 800",
        ),
        FilmStock(
            id = "negative_new_kodak_tri_x_400_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Tri-X 400 -",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tri_mx_400_m,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tri-X 400 -",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_160_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 -",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_160_m,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 -",
        ),
        FilmStock(
            id = "negative_new_kodak_portra_160_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 ++",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_portra_160_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 ++",
        ),
        FilmStock(
            id = "negative_new_kodak_tmax_3200_3",
            brand = FilmBrand.KODAK,
            name = "Kodak Tmax 3200 -",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tmax_3200_m,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tmax 3200 -",
        ),
        FilmStock(
            id = "negative_new_kodak_tri_x_400_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Tri-X 400 +",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tri_mx_400_p,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tri-X 400 +",
        ),
        FilmStock(
            id = "negative_new_kodak_tmax_3200_4",
            brand = FilmBrand.KODAK,
            name = "Kodak Tmax 3200 ++",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_new_kodak_tmax_3200_pp,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Tmax 3200 ++",
        ),
        FilmStock(
            id = "bw_kodak_t_max_400",
            brand = FilmBrand.KODAK,
            name = "Kodak T-Max 400",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_kodak_t_mmax_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Kodak T-Max 400",
        ),
        FilmStock(
            id = "bw_kodak_t_max_100",
            brand = FilmBrand.KODAK,
            name = "Kodak T-Max 100",
            iso = 100,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_kodak_t_mmax_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Kodak T-Max 100",
        ),
        FilmStock(
            id = "bw_kodak_t_max_3200",
            brand = FilmBrand.KODAK,
            name = "Kodak T-Max 3200",
            iso = 200,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_kodak_t_mmax_3200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Kodak T-Max 3200",
        ),
        FilmStock(
            id = "bw_kodak_tri_x_400",
            brand = FilmBrand.KODAK,
            name = "Kodak Tri-X 400",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_kodak_tri_mx_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Kodak Tri-X 400",
        ),
        FilmStock(
            id = "bw_kodak_bw_400_cn",
            brand = FilmBrand.KODAK,
            name = "Kodak Bw 400 Cn",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.BLACK_AND_WHITE,
            lutResId = R.raw.lut_bw_kodak_bw_400_cn,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Kodak Bw 400 Cn",
        ),
        FilmStock(
            id = "bw_kodak_hie_hs_infra",
            brand = FilmBrand.KODAK,
            name = "Kodak Hie Hs Infra",
            iso = 400,
            isBlackAndWhite = true,
            category = FilmCategory.INFRARED,
            lutResId = R.raw.lut_bw_kodak_hie_hs_infra,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 0.00f,
            contrast = 0.95f,
            shadowLift = 5.0f,
            accentColor = Color(0xFFCCCCCC),
            description = "Kodak Hie Hs Infra",
        ),
        FilmStock(
            id = "colorslide_kodak_elite_chrome_400",
            brand = FilmBrand.KODAK,
            name = "Kodak Elite Chrome 400",
            iso = 400,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_elite_chrome_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Elite Chrome 400",
        ),
        FilmStock(
            id = "colorslide_kodak_ektachrome_100_vs_generic",
            brand = FilmBrand.KODAK,
            name = "Kodak Ektachrome 100 Vs Generic",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_ektachrome_100_vs_generic,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Ektachrome 100 Vs Generic",
        ),
        FilmStock(
            id = "colorslide_kodak_kodachrome_25",
            brand = FilmBrand.KODAK,
            name = "Kodak Kodachrome 25",
            iso = 25,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_kodachrome_25,
            lutType = LutType.CUBE,
            grainAmount = 0.04f,
            grainSize = 1.01f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Kodachrome 25",
        ),
        FilmStock(
            id = "colorslide_kodak_kodachrome_200",
            brand = FilmBrand.KODAK,
            name = "Kodak Kodachrome 200",
            iso = 200,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_kodachrome_200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Kodachrome 200",
        ),
        FilmStock(
            id = "colorslide_kodak_kodachrome_64",
            brand = FilmBrand.KODAK,
            name = "Kodak Kodachrome 64",
            iso = 64,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_kodachrome_64,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Kodachrome 64",
        ),
        FilmStock(
            id = "colorslide_kodak_elite_extracolor_100",
            brand = FilmBrand.KODAK,
            name = "Kodak Elite Extracolor 100",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_elite_extracolor_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Elite Extracolor 100",
        ),
        FilmStock(
            id = "colorslide_kodak_e_100_gx_ektachrome_100",
            brand = FilmBrand.KODAK,
            name = "Kodak E-100 Gx Ektachrome 100",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_e_m100_gx_ektachrome_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak E-100 Gx Ektachrome 100",
        ),
        FilmStock(
            id = "colorslide_kodak_ektachrome_100_vs",
            brand = FilmBrand.KODAK,
            name = "Kodak Ektachrome 100 Vs",
            iso = 100,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_ektachrome_100_vs,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Ektachrome 100 Vs",
        ),
        FilmStock(
            id = "colorslide_kodak_elite_chrome_200",
            brand = FilmBrand.KODAK,
            name = "Kodak Elite Chrome 200",
            iso = 200,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_elite_chrome_200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Elite Chrome 200",
        ),
        FilmStock(
            id = "colorslide_kodak_kodachrome_64_generic",
            brand = FilmBrand.KODAK,
            name = "Kodak Kodachrome 64 Generic",
            iso = 64,
            category = FilmCategory.SLIDE,
            lutResId = R.raw.lut_colorslide_kodak_kodachrome_64_generic,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.03f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.35f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Kodachrome 64 Generic",
        ),
        FilmStock(
            id = "negative_color_kodak_portra_160_vc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Vc",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_kodak_portra_160_vc,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Vc",
        ),
        FilmStock(
            id = "negative_color_kodak_elite_color_200",
            brand = FilmBrand.KODAK,
            name = "Kodak Elite Color 200",
            iso = 200,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_kodak_elite_color_200,
            lutType = LutType.CUBE,
            grainAmount = 0.06f,
            grainSize = 1.09f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Elite Color 200",
        ),
        FilmStock(
            id = "negative_color_kodak_elite_100_xpro",
            brand = FilmBrand.KODAK,
            name = "Kodak Elite 100 Xpro",
            iso = 100,
            category = FilmCategory.CROSS_PROCESS,
            lutResId = R.raw.lut_negative_color_kodak_elite_100_xpro,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 1.15f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Elite 100 Xpro",
        ),
        FilmStock(
            id = "negative_color_kodak_portra_160_nc",
            brand = FilmBrand.KODAK,
            name = "Kodak Portra 160 Nc",
            iso = 160,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_kodak_portra_160_nc,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.07f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Portra 160 Nc",
        ),
        FilmStock(
            id = "negative_color_kodak_ektar_100",
            brand = FilmBrand.KODAK,
            name = "Kodak Ektar 100",
            iso = 100,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_kodak_ektar_100,
            lutType = LutType.CUBE,
            grainAmount = 0.05f,
            grainSize = 1.04f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Ektar 100",
        ),
        FilmStock(
            id = "negative_color_kodak_elite_color_400",
            brand = FilmBrand.KODAK,
            name = "Kodak Elite Color 400",
            iso = 400,
            category = FilmCategory.COLOR,
            lutResId = R.raw.lut_negative_color_kodak_elite_color_400,
            lutType = LutType.CUBE,
            grainAmount = 0.07f,
            grainSize = 1.18f,
            lightLeakProbability = 0.05f,
            colorTempShift = 0,
            highlightRolloff = 0.40f,
            saturation = 1.00f,
            contrast = 0.95f,
            shadowLift = 4.0f,
            accentColor = Color(0xFFE8C070),
            description = "Kodak Elite Color 400",
        ),
)
